name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Add permissions for actions
permissions:
  contents: read
  actions: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    # Add permissions for this job
    permissions:
      contents: read
      actions: write
      packages: read
      id-token: write

    steps:
    - uses: actions/checkout@v3  # Updated to v3
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pylint
        
    - name: Run linter
      run: pylint --disable=R,C xgboost_script.py
        
    - name: Run tests
      run: pytest tests/ -v
    
    - name: Create output directory
      run: mkdir -p model_outputs
      
    - name: Run training pipeline
      run: python xgboost_script.py

    - name: Check artifacts
      run: |
        ls -l model_outputs/
        test -f model_outputs/classification_model.pkl
        test -f model_outputs/confusion_matrix.png

    - name: Upload artifacts
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: model-artifacts
        path: model_outputs/
        if-no-files-found: error

    - name: Validate model
      run: pytest tests/test_model_validation.py