name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Required permissions for the entire workflow
permissions:
  contents: read
  actions: read
  packages: read
  id-token: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    # Job-specific permissions (override workflow permissions if needed)
    permissions:
      contents: read
      actions: read
      packages: read
      id-token: write
      checks: write
      pull-requests: write
      statuses: write
      deployments: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pylint
        
    - name: Run linter
      run: pylint --disable=R,C xgboost_script.py
        
    - name: Run tests
      run: pytest tests/ -v
    
    - name: Create output directory
      run: mkdir -p model_outputs
      
    - name: Run training pipeline
      run: python xgboost_script.py

    - name: Check artifacts
      run: |
        ls -l model_outputs/
        test -f model_outputs/classification_model.pkl
        test -f model_outputs/confusion_matrix.png

    - name: Upload artifacts
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb  # Stable commit SHA for v3
      with:
        name: model-artifacts
        path: model_outputs/
        if-no-files-found: error
        retention-days: 5

    - name: Validate model
      run: pytest tests/test_model_validation.py